# -*- coding: utf-8 -*-
##################################################
# GNU Radio Python Flow Graph
# Title: Streampsdvolk
# Generated: Tue May 16 11:13:12 2017
##################################################

from gnuradio import gr
from gnuradio.filter import firdes
import utils


class streampsdvolk(gr.hier_block2):

    def __init__(self, alpha=0.8, fft_len=1024, samp_rate=1e6):
        gr.hier_block2.__init__(
            self, "Streampsdvolk",
            gr.io_signaturev(40, 40, [gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1, gr.sizeof_gr_complex*1]),
            gr.io_signaturev(40, 40, [gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len, gr.sizeof_float*fft_len]),
        )

        ##################################################
        # Parameters
        ##################################################
        self.alpha = alpha
        self.fft_len = fft_len
        self.samp_rate = samp_rate

        ##################################################
        # Blocks
        ##################################################
        self.utils_psd_cvf_0_9 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_8 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_7 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_6 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_5 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_4 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_38 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_37 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_36 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_35 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_34 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_33 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_32 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_31 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_30 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_3 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_29 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_28 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_27 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_26 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_25 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_24 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_23 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_22 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_21 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_20 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_2 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_19 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_18 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_17 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_16 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_15 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_14 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_13 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_12 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_11 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_10 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_1 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0_0 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)
        self.utils_psd_cvf_0 = utils.psd_cvf(samp_rate,  fft_len, firdes.WIN_BLACKMAN_hARRIS, alpha)

        ##################################################
        # Connections
        ##################################################
        self.connect((self, 0), (self.utils_psd_cvf_0, 0))
        self.connect((self, 1), (self.utils_psd_cvf_0_0, 0))
        self.connect((self, 2), (self.utils_psd_cvf_0_1, 0))
        self.connect((self, 3), (self.utils_psd_cvf_0_10, 0))
        self.connect((self, 4), (self.utils_psd_cvf_0_11, 0))
        self.connect((self, 5), (self.utils_psd_cvf_0_12, 0))
        self.connect((self, 6), (self.utils_psd_cvf_0_13, 0))
        self.connect((self, 7), (self.utils_psd_cvf_0_14, 0))
        self.connect((self, 8), (self.utils_psd_cvf_0_15, 0))
        self.connect((self, 9), (self.utils_psd_cvf_0_16, 0))
        self.connect((self, 10), (self.utils_psd_cvf_0_17, 0))
        self.connect((self, 11), (self.utils_psd_cvf_0_18, 0))
        self.connect((self, 12), (self.utils_psd_cvf_0_19, 0))
        self.connect((self, 13), (self.utils_psd_cvf_0_2, 0))
        self.connect((self, 14), (self.utils_psd_cvf_0_20, 0))
        self.connect((self, 15), (self.utils_psd_cvf_0_21, 0))
        self.connect((self, 16), (self.utils_psd_cvf_0_22, 0))
        self.connect((self, 17), (self.utils_psd_cvf_0_23, 0))
        self.connect((self, 18), (self.utils_psd_cvf_0_24, 0))
        self.connect((self, 19), (self.utils_psd_cvf_0_25, 0))
        self.connect((self, 20), (self.utils_psd_cvf_0_26, 0))
        self.connect((self, 21), (self.utils_psd_cvf_0_27, 0))
        self.connect((self, 22), (self.utils_psd_cvf_0_28, 0))
        self.connect((self, 23), (self.utils_psd_cvf_0_29, 0))
        self.connect((self, 24), (self.utils_psd_cvf_0_3, 0))
        self.connect((self, 25), (self.utils_psd_cvf_0_30, 0))
        self.connect((self, 26), (self.utils_psd_cvf_0_31, 0))
        self.connect((self, 27), (self.utils_psd_cvf_0_32, 0))
        self.connect((self, 28), (self.utils_psd_cvf_0_33, 0))
        self.connect((self, 29), (self.utils_psd_cvf_0_34, 0))
        self.connect((self, 30), (self.utils_psd_cvf_0_35, 0))
        self.connect((self, 31), (self.utils_psd_cvf_0_36, 0))
        self.connect((self, 32), (self.utils_psd_cvf_0_37, 0))
        self.connect((self, 33), (self.utils_psd_cvf_0_38, 0))
        self.connect((self, 34), (self.utils_psd_cvf_0_4, 0))
        self.connect((self, 35), (self.utils_psd_cvf_0_5, 0))
        self.connect((self, 36), (self.utils_psd_cvf_0_6, 0))
        self.connect((self, 37), (self.utils_psd_cvf_0_7, 0))
        self.connect((self, 38), (self.utils_psd_cvf_0_8, 0))
        self.connect((self, 39), (self.utils_psd_cvf_0_9, 0))
        self.connect((self.utils_psd_cvf_0, 0), (self, 0))
        self.connect((self.utils_psd_cvf_0_0, 0), (self, 1))
        self.connect((self.utils_psd_cvf_0_1, 0), (self, 2))
        self.connect((self.utils_psd_cvf_0_10, 0), (self, 3))
        self.connect((self.utils_psd_cvf_0_11, 0), (self, 4))
        self.connect((self.utils_psd_cvf_0_12, 0), (self, 5))
        self.connect((self.utils_psd_cvf_0_13, 0), (self, 6))
        self.connect((self.utils_psd_cvf_0_14, 0), (self, 7))
        self.connect((self.utils_psd_cvf_0_15, 0), (self, 8))
        self.connect((self.utils_psd_cvf_0_16, 0), (self, 9))
        self.connect((self.utils_psd_cvf_0_17, 0), (self, 10))
        self.connect((self.utils_psd_cvf_0_18, 0), (self, 11))
        self.connect((self.utils_psd_cvf_0_19, 0), (self, 12))
        self.connect((self.utils_psd_cvf_0_2, 0), (self, 13))
        self.connect((self.utils_psd_cvf_0_20, 0), (self, 14))
        self.connect((self.utils_psd_cvf_0_21, 0), (self, 15))
        self.connect((self.utils_psd_cvf_0_22, 0), (self, 16))
        self.connect((self.utils_psd_cvf_0_23, 0), (self, 17))
        self.connect((self.utils_psd_cvf_0_24, 0), (self, 18))
        self.connect((self.utils_psd_cvf_0_25, 0), (self, 19))
        self.connect((self.utils_psd_cvf_0_26, 0), (self, 20))
        self.connect((self.utils_psd_cvf_0_27, 0), (self, 21))
        self.connect((self.utils_psd_cvf_0_28, 0), (self, 22))
        self.connect((self.utils_psd_cvf_0_29, 0), (self, 23))
        self.connect((self.utils_psd_cvf_0_3, 0), (self, 24))
        self.connect((self.utils_psd_cvf_0_30, 0), (self, 25))
        self.connect((self.utils_psd_cvf_0_31, 0), (self, 26))
        self.connect((self.utils_psd_cvf_0_32, 0), (self, 27))
        self.connect((self.utils_psd_cvf_0_33, 0), (self, 28))
        self.connect((self.utils_psd_cvf_0_34, 0), (self, 29))
        self.connect((self.utils_psd_cvf_0_35, 0), (self, 30))
        self.connect((self.utils_psd_cvf_0_36, 0), (self, 31))
        self.connect((self.utils_psd_cvf_0_37, 0), (self, 32))
        self.connect((self.utils_psd_cvf_0_38, 0), (self, 33))
        self.connect((self.utils_psd_cvf_0_4, 0), (self, 34))
        self.connect((self.utils_psd_cvf_0_5, 0), (self, 35))
        self.connect((self.utils_psd_cvf_0_6, 0), (self, 36))
        self.connect((self.utils_psd_cvf_0_7, 0), (self, 37))
        self.connect((self.utils_psd_cvf_0_8, 0), (self, 38))
        self.connect((self.utils_psd_cvf_0_9, 0), (self, 39))

    def get_alpha(self):
        return self.alpha

    def set_alpha(self, alpha):
        self.alpha = alpha
        self.utils_psd_cvf_0_9.set_average(self.alpha)
        self.utils_psd_cvf_0_8.set_average(self.alpha)
        self.utils_psd_cvf_0_7.set_average(self.alpha)
        self.utils_psd_cvf_0_6.set_average(self.alpha)
        self.utils_psd_cvf_0_5.set_average(self.alpha)
        self.utils_psd_cvf_0_4.set_average(self.alpha)
        self.utils_psd_cvf_0_38.set_average(self.alpha)
        self.utils_psd_cvf_0_37.set_average(self.alpha)
        self.utils_psd_cvf_0_36.set_average(self.alpha)
        self.utils_psd_cvf_0_35.set_average(self.alpha)
        self.utils_psd_cvf_0_34.set_average(self.alpha)
        self.utils_psd_cvf_0_33.set_average(self.alpha)
        self.utils_psd_cvf_0_32.set_average(self.alpha)
        self.utils_psd_cvf_0_31.set_average(self.alpha)
        self.utils_psd_cvf_0_30.set_average(self.alpha)
        self.utils_psd_cvf_0_3.set_average(self.alpha)
        self.utils_psd_cvf_0_29.set_average(self.alpha)
        self.utils_psd_cvf_0_28.set_average(self.alpha)
        self.utils_psd_cvf_0_27.set_average(self.alpha)
        self.utils_psd_cvf_0_26.set_average(self.alpha)
        self.utils_psd_cvf_0_25.set_average(self.alpha)
        self.utils_psd_cvf_0_24.set_average(self.alpha)
        self.utils_psd_cvf_0_23.set_average(self.alpha)
        self.utils_psd_cvf_0_22.set_average(self.alpha)
        self.utils_psd_cvf_0_21.set_average(self.alpha)
        self.utils_psd_cvf_0_20.set_average(self.alpha)
        self.utils_psd_cvf_0_2.set_average(self.alpha)
        self.utils_psd_cvf_0_19.set_average(self.alpha)
        self.utils_psd_cvf_0_18.set_average(self.alpha)
        self.utils_psd_cvf_0_17.set_average(self.alpha)
        self.utils_psd_cvf_0_16.set_average(self.alpha)
        self.utils_psd_cvf_0_15.set_average(self.alpha)
        self.utils_psd_cvf_0_14.set_average(self.alpha)
        self.utils_psd_cvf_0_13.set_average(self.alpha)
        self.utils_psd_cvf_0_12.set_average(self.alpha)
        self.utils_psd_cvf_0_11.set_average(self.alpha)
        self.utils_psd_cvf_0_10.set_average(self.alpha)
        self.utils_psd_cvf_0_1.set_average(self.alpha)
        self.utils_psd_cvf_0_0.set_average(self.alpha)
        self.utils_psd_cvf_0.set_average(self.alpha)

    def get_fft_len(self):
        return self.fft_len

    def set_fft_len(self, fft_len):
        self.fft_len = fft_len
        self.utils_psd_cvf_0_9.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_8.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_7.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_6.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_5.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_4.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_38.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_37.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_36.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_35.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_34.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_33.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_32.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_31.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_30.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_3.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_29.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_28.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_27.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_26.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_25.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_24.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_23.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_22.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_21.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_20.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_2.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_19.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_18.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_17.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_16.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_15.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_14.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_13.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_12.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_11.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_10.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_1.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0_0.set_fft_len( self.fft_len)
        self.utils_psd_cvf_0.set_fft_len( self.fft_len)

    def get_samp_rate(self):
        return self.samp_rate

    def set_samp_rate(self, samp_rate):
        self.samp_rate = samp_rate
        self.utils_psd_cvf_0_9.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_8.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_7.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_6.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_5.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_4.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_38.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_37.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_36.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_35.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_34.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_33.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_32.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_31.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_30.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_3.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_29.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_28.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_27.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_26.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_25.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_24.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_23.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_22.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_21.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_20.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_2.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_19.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_18.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_17.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_16.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_15.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_14.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_13.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_12.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_11.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_10.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_1.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0_0.set_samp_rate(self.samp_rate)
        self.utils_psd_cvf_0.set_samp_rate(self.samp_rate)
